/**
 * Step 3 of the vocab-image pipeline.
 *
 * Downloads the photos you picked in the review gallery (tools/data/image-selections.json),
 * optimizes each to a small webp, and writes them to public/images/vocab/<slug>.webp.
 * Then generates:
 *   - src/data/vocab/images.ts   — typed `en -> /images/vocab/<slug>.webp` manifest
 *   - public/images/vocab/CREDITS.json — photographer + source page per image
 *
 * Usage:
 *   node tools/scripts/images/download-images.mjs
 *
 * Safe to re-run: existing image files are skipped; the manifest/credits are
 * always regenerated from the full selections file.
 */

import { readFileSync, writeFileSync, existsSync, mkdirSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";
import { slugify, downloadImage } from "../../lib/images.mjs";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..", "..", "..");
const SELECTIONS_PATH = join(ROOT, "tools", "data", "image-selections.json");
const OUT_DIR = join(ROOT, "public", "images", "vocab");
const MANIFEST_PATH = join(ROOT, "src", "data", "vocab", "images.ts");
const CREDITS_PATH = join(OUT_DIR, "CREDITS.json");
const SIZE = 400; // square-ish flashcard size

if (!existsSync(SELECTIONS_PATH)) {
  console.error("No image-selections.json — run review-server.mjs and pick some images first.");
  process.exit(1);
}

const selections = JSON.parse(readFileSync(SELECTIONS_PATH, "utf8"));
mkdirSync(OUT_DIR, { recursive: true });

const manifest = {}; // en -> public path
const credits = {}; // en -> { source, author, page }
let downloaded = 0,
  skipped = 0;

for (const [en, choice] of Object.entries(selections)) {
  if (!choice || choice.skip || choice.none) continue; // skip = deferred, none = intentionally no image
  const slug = slugify(en);
  const file = `${slug}.webp`;
  const outPath = join(OUT_DIR, file);
  manifest[en] = `/images/vocab/${file}`;
  credits[en] = { source: choice.source, author: choice.author || null, page: choice.page || null };

  if (existsSync(outPath)) {
    skipped++;
    continue;
  }
  try {
    await downloadImage(choice.full || choice.thumb, outPath, { width: SIZE, height: SIZE, fit: "cover" });
    downloaded++;
    console.log(`  wrote ${file}  (${en})`);
  } catch (e) {
    console.error(`  ERROR ${en}: ${e.message}`);
    delete manifest[en];
    delete credits[en];
  }
}

// ── generated manifest (sorted for stable diffs) ──
const entries = Object.keys(manifest)
  .sort()
  .map((en) => `  ${JSON.stringify(en)}: ${JSON.stringify(manifest[en])},`)
  .join("\n");
const ts = `// AUTO-GENERATED by tools/scripts/images/download-images.mjs — do not edit by hand.
// Maps vocab word (en) -> public image path. Regenerate after picking images.
export const vocabImages: Record<string, string> = {
${entries}
};
`;
writeFileSync(MANIFEST_PATH, ts);
writeFileSync(CREDITS_PATH, JSON.stringify(credits, null, 2));

console.log(
  `Done. ${downloaded} downloaded, ${skipped} already present, ` +
    `${Object.keys(manifest).length} in manifest.`
);
console.log(`Manifest: ${MANIFEST_PATH}`);
