// AUTO-GENERATED by tools/scripts/sfx/sfx-review-server.mjs — do not edit by hand.
// Maps a sound key -> approved ElevenLabs clip path. Keys not listed here fall
// back to the procedural Web Audio version in src/lib/sounds.ts.
// Regenerate by approving clips in the SFX review server.
export const sfxAssets: Record<string, string> = {
};
